### ISSUE TITLE
Support for Sass-Maps

### ISSUE THREAD

**Issue by natterstefan** [madyankin/postcss-each#37]
Hey @madyankin,

first of all, thanks for creating this plugin, and thanks to all the contributors as well. I got a question and I saw that I was not the first one who asked this (see https://github.com/madyankin/postcss-each/issues/26).

Sass Maps are not supported at the moment, are they?

## Example

```scss
// @see https://www.digitalocean.com/community/tutorials/sass-each-loops
// @see https://www.digitalocean.com/community/tutorials/sass-sass-maps
$map: (
  h1: 20px,
  h2: 16px,
  h3: 14px
);

@each $element, $size in $map {
  #{$element} {
    font-size: $size;
  }
}
```

Thanks for your help in advance, I appreciate it.
